import os

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()


class LLMService:
    """
    Central LLM service for InsightFlow AI.

    Instead of every agent directly connecting to Gemini,
    agents will use this service.

    Future users:
        - SQL Agent
        - Insight Agent
        - Dashboard Agent
        - Report Agent
        - Chat Agent
    """

    def __init__(
        self,
        model_name="gemini-3.6-flash"
        
    ):

        # ====================================================
        # GET API KEY FROM .env
        # ====================================================

        api_key = os.getenv(
            "GOOGLE_API_KEY"
        )

        if not api_key:

            raise ValueError(
                "GOOGLE_API_KEY was not found. "
                "Check your .env file."
            )

        # ====================================================
        # CREATE GEMINI LLM
        # ====================================================

        self.llm = ChatGoogleGenerativeAI(
            model=model_name,
            google_api_key=api_key
           
        )


    # ========================================================
    # GENERATE RESPONSE
    # ========================================================

    def generate(self, prompt):

        """
        Send a prompt to Gemini and return only
        the text generated by the model.
        """

        if not isinstance(prompt, str):
            raise TypeError(
                "Prompt must be a string."
            )

        if not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        response = self.llm.invoke(prompt)

        content = response.content

        # Sometimes Gemini/LangChain returns plain text
        if isinstance(content, str):
            return content

        # Sometimes it returns structured content blocks
        if isinstance(content, list):

            text_parts = []

            for block in content:

                if isinstance(block, dict):

                    if block.get("type") == "text":

                        text = block.get("text", "")

                        if text:
                            text_parts.append(text)

            return "\n".join(text_parts)

        # Fallback
        return str(content)