import json

from pydantic import BaseModel, Field

from backend.orchestration.state import AgentState
from backend.services.llm_service import LLMService
from backend.orchestration.tool_registry import (
    get_available_tools,
)


class AnalyticsPlan(BaseModel):
    """
    Structured execution plan generated by the LLM.
    """

    intent: str = Field(
        description=(
            "Short analytical intent such as "
            "aggregation, visualization, "
            "relationship_analysis, dataset_context, "
            "or general_analysis."
        )
    )

    tools: list[str] = Field(
        description=(
            "Ordered list of tools required "
            "to answer the request."
        )
    )

    reasoning: str = Field(
        description=(
            "Short explanation of why these tools "
            "were selected."
        )
    )


def _fallback_plan(
    question: str
) -> AnalyticsPlan:
    """
    Deterministic fallback when the LLM planner
    is unavailable.

    This keeps the application operational during
    quota exhaustion, API failure, or invalid output.
    """

    question_lower = question.lower()

    tools = []

    if any(
        word in question_lower
        for word in [
            "column",
            "columns",
            "schema",
            "quality",
            "dataset",
            "rows",
            "structure",
        ]
    ):
        tools.append(
            "dataset_context"
        )

    if any(
        word in question_lower
        for word in [
            "average",
            "avg",
            "sum",
            "total",
            "count",
            "highest",
            "lowest",
            "top",
            "bottom",
            "compare",
            "group",
            "grouped",
            "trend",
            "relationship",
            "correlation",
            "distribution",
            "performance",
        ]
    ):
        tools.append(
            "sql"
        )

    if any(
        word in question_lower
        for word in [
            "plot",
            "chart",
            "graph",
            "visualize",
            "visualization",
            "scatter",
            "box plot",
            "boxplot",
            "histogram",
            "heatmap",
            "bar chart",
            "line chart",
            "violin",
            "kpi",
        ]
    ):
        tools.append(
            "visualization"
        )

    if any(
        word in question_lower
        for word in [
            "explain",
            "insight",
            "interpret",
            "why",
            "recommend",
            "summary",
            "summarize",
            "analyze",
            "analyse",
        ]
    ):
        tools.append(
            "insight"
        )

    if not tools:
        tools = [
            "sql",
            "insight",
        ]

    tools = list(
        dict.fromkeys(tools)
    )

    return AnalyticsPlan(
        intent="fallback_analysis",

        tools=tools,

        reasoning=(
            "Deterministic fallback plan used because "
            "the LLM planner was unavailable."
        ),
    )


def _build_planner_prompt(
    question: str
) -> str:

    available_tools = (
        get_available_tools()
    )

    return f"""
You are the planning agent for InsightFlow AI.

Your job is NOT to answer the user's analytical question.

Your job is to decide which tools should be executed and
in what order.

USER QUESTION:
{question}

AVAILABLE TOOLS:
{available_tools}

TOOL CAPABILITIES:

dataset_context:
Use for dataset metadata, columns, schema, dimensions,
existing quality information, anomalies, EDA results,
statistical findings, and available charts.

sql:
Use for calculations and data retrieval such as filtering,
aggregation, grouping, ranking, totals, averages, counts,
comparisons, and analytical queries.

visualization:
Use when the user explicitly requests a chart, plot,
graph, visualization, distribution visualization,
relationship visualization, trend visualization, or KPI.

insight:
Use when interpretation, explanation, recommendations,
summary, analytical findings, or business insight is needed.

RULES:

1. Return ONLY valid JSON.

2. Use only tools from:
{available_tools}

3. Keep the plan minimal.
Do not invoke unnecessary tools.

4. Preserve execution dependencies.

For example:
SQL should occur before visualization when the requested
visualization depends on an analytical SQL result.

SQL should occur before insight when the insight depends
on query results.

5. dataset_context does NOT need to be called for every
request.

6. Do not answer the analytical question yourself.

7. The JSON must have exactly this structure:

{{
    "intent": "short_intent_name",
    "tools": ["tool_1", "tool_2"],
    "reasoning": "short planning explanation"
}}
""".strip()


def _parse_plan(
    raw_response
) -> AnalyticsPlan:

    if isinstance(
        raw_response,
        AnalyticsPlan
    ):
        return raw_response

    if isinstance(
        raw_response,
        dict
    ):
        return AnalyticsPlan.model_validate(
            raw_response
        )

    text = str(
        raw_response
    ).strip()

    if text.startswith("```"):

        text = text.replace(
            "```json",
            ""
        )

        text = text.replace(
            "```",
            ""
        )

        text = text.strip()

    parsed = json.loads(
        text
    )

    return AnalyticsPlan.model_validate(
        parsed
    )


def planner_node(
    state: AgentState
) -> dict:

    question = (
        state.get(
            "question",
            ""
        )
        .strip()
    )

    trace = list(
        state.get(
            "trace",
            []
        )
    )

    available_tools = set(
        get_available_tools()
    )

    try:

        llm_service = LLMService()

        prompt = _build_planner_prompt(
            question
        )

        # IMPORTANT:
        # This must call the method your current
        # LLMService exposes for plain text generation.
        raw_response = (
            llm_service.generate(
                prompt
            )
        )

        plan_result = _parse_plan(
            raw_response
        )

        valid_tools = [
            tool_name
            for tool_name in plan_result.tools
            if tool_name in available_tools
        ]

        valid_tools = list(
            dict.fromkeys(valid_tools)
        )

        if not valid_tools:
            raise ValueError(
                "Planner returned no valid tools."
            )

        planner_source = "llm"

    except Exception as exc:

        plan_result = _fallback_plan(
            question
        )

        valid_tools = (
            plan_result.tools
        )

        planner_source = "fallback"

        planner_error = str(
            exc
        )

    else:

        planner_error = None

    trace.append({
        "node": "planner",

        "status": "success",

        "source": planner_source,

        "intent": (
            plan_result.intent
        ),

        "plan": valid_tools,

        "reasoning": (
            plan_result.reasoning
        ),

        "error": planner_error,
    })

    return {
        "intent":
            plan_result.intent,

        "plan":
            valid_tools,

        "plan_reasoning":
            plan_result.reasoning,

        "planner_source":
            planner_source,

        "planner_error":
            planner_error,


        "current_step": (
            valid_tools[0]
            if valid_tools
            else None
        ),

        "trace":
            trace,
    }