import json

from pydantic import BaseModel, Field

from backend.orchestration.state import AgentState

from backend.services.llm_service import (
    LLMService,
)

from backend.orchestration.tool_registry import (
    get_available_tools,
    get_tool_descriptions,
)


# ============================================================
# ANALYTICS PLAN
# ============================================================

class AnalyticsPlan(BaseModel):
    """
    Structured execution plan generated by the LLM.
    """

    intent: str = Field(
        description=(
            "Short analytical intent describing "
            "what the user wants to accomplish."
        )
    )

    tools: list[str] = Field(
        description=(
            "Ordered list of tools required "
            "to answer the request."
        )
    )

    reasoning: str = Field(
        description=(
            "Short explanation of why these tools "
            "were selected."
        )
    )


# ============================================================
# FALLBACK PLAN
# ============================================================

def _fallback_plan(
    question: str
) -> AnalyticsPlan:
    """
    Deterministic fallback when the LLM planner
    is unavailable.

    This keeps the application operational during
    quota exhaustion, API failure, or invalid output.
    """

    question_lower = question.lower()

    tools = []

    # --------------------------------------------------------
    # Dataset context
    # --------------------------------------------------------

    if any(
        word in question_lower
        for word in [
            "column",
            "columns",
            "schema",
            "quality",
            "dataset",
            "rows",
            "structure",
        ]
    ):
        tools.append(
            "dataset_context"
        )

    # --------------------------------------------------------
    # SQL analysis
    # --------------------------------------------------------

    if any(
        word in question_lower
        for word in [
            "average",
            "avg",
            "sum",
            "total",
            "count",
            "highest",
            "lowest",
            "top",
            "bottom",
            "compare",
            "group",
            "grouped",
            "trend",
            "relationship",
            "correlation",
            "distribution",
            "performance",
        ]
    ):
        tools.append(
            "sql"
        )

    # --------------------------------------------------------
    # Visualization
    # --------------------------------------------------------

    if any(
        word in question_lower
        for word in [
            "plot",
            "chart",
            "graph",
            "visualize",
            "visualization",
            "scatter",
            "box plot",
            "boxplot",
            "histogram",
            "heatmap",
            "bar chart",
            "line chart",
            "violin",
            "kpi",
        ]
    ):
        tools.append(
            "visualization"
        )

    # --------------------------------------------------------
    # Insight
    # --------------------------------------------------------

    if any(
        word in question_lower
        for word in [
            "explain",
            "insight",
            "interpret",
            "why",
            "recommend",
            "summary",
            "summarize",
            "analyze",
            "analyse",
        ]
    ):
        tools.append(
            "insight"
        )

    # --------------------------------------------------------
    # Default fallback
    # --------------------------------------------------------

    if not tools:

        tools = [
            "sql",
            "insight",
        ]

    # Remove duplicates while preserving order.

    tools = list(
        dict.fromkeys(
            tools
        )
    )

    return AnalyticsPlan(
        intent="fallback_analysis",

        tools=tools,

        reasoning=(
            "Deterministic fallback plan used because "
            "the LLM planner was unavailable."
        ),
    )


# ============================================================
# BUILD AVAILABLE TOOL CATALOG
# ============================================================

def _build_tool_catalog() -> str:
    """
    Build the tool catalog presented to the LLM planner
    dynamically from the central tool registry.

    This prevents the planner from maintaining its own
    hard-coded list of available capabilities.
    """

    tool_descriptions = (
        get_tool_descriptions()
    )

    catalog = []

    for (
        tool_name,
        metadata
    ) in tool_descriptions.items():

        catalog.append({
            "name":
                tool_name,

            "description":
                metadata.get(
                    "description",
                    ""
                ),

            "inputs":
                metadata.get(
                    "inputs",
                    {}
                ),

            "outputs":
                metadata.get(
                    "outputs",
                    {}
                ),

            "dependencies":
                metadata.get(
                    "dependencies",
                    []
                ),
        })

    return json.dumps(
        catalog,
        indent=2
    )


# ============================================================
# BUILD PLANNER PROMPT
# ============================================================

def _build_planner_prompt(
    question: str
) -> str:
    """
    Build the LLM planning prompt using capabilities
    discovered dynamically from the tool registry.
    """

    tool_catalog = (
        _build_tool_catalog()
    )

    return f"""
You are the planning agent for InsightFlow AI.

Your job is NOT to answer the user's analytical question.

Your job is to decide which available tools should be
executed and in what order.

USER QUESTION:

{question}


AVAILABLE TOOLS:

{tool_catalog}


RULES:

1. Return ONLY valid JSON.

2. Do not use markdown or code fences.

3. Use only tools listed in AVAILABLE TOOLS.

4. Keep the execution plan minimal.
Do not invoke unnecessary tools.

5. Preserve execution dependencies.

If one tool depends on the output of another tool,
the dependency must appear earlier in the plan.

Use the dependency metadata provided in AVAILABLE TOOLS
when deciding execution order.

6. Do not invent tool names.

7. Do not assume capabilities that are not described
in AVAILABLE TOOLS.

8. Do not answer the analytical question yourself.

9. Order the tools exactly in the sequence in which
they should execute.

10. The JSON must have exactly this structure:

{{
    "intent": "short_intent_name",
    "tools": ["tool_1", "tool_2"],
    "reasoning": "short planning explanation"
}}
""".strip()


# ============================================================
# PARSE PLAN
# ============================================================

def _parse_plan(
    raw_response
) -> AnalyticsPlan:
    """
    Parse an LLM response into AnalyticsPlan.
    """

    if isinstance(
        raw_response,
        AnalyticsPlan
    ):
        return raw_response

    if isinstance(
        raw_response,
        dict
    ):
        return AnalyticsPlan.model_validate(
            raw_response
        )

    text = str(
        raw_response
    ).strip()

    # --------------------------------------------------------
    # Remove markdown JSON fences if the model added them
    # despite the prompt instructions.
    # --------------------------------------------------------

    if text.startswith(
        "```"
    ):

        text = text.replace(
            "```json",
            ""
        )

        text = text.replace(
            "```",
            ""
        )

        text = text.strip()

    parsed = json.loads(
        text
    )

    return AnalyticsPlan.model_validate(
        parsed
    )


# ============================================================
# PLANNER NODE
# ============================================================

def planner_node(
    state: AgentState
) -> dict:
    """
    Generate an execution plan for the current
    analytical request.
    """

    question = (
        state.get(
            "question",
            ""
        )
        .strip()
    )

    trace = list(
        state.get(
            "trace",
            []
        )
    )

    # --------------------------------------------------------
    # Registry is the source of truth for valid tool names.
    # --------------------------------------------------------

    available_tools = set(
        get_available_tools()
    )

    try:

        # ====================================================
        # CALL LLM PLANNER
        # ====================================================

        llm_service = (
            LLMService()
        )

        prompt = (
            _build_planner_prompt(
                question
            )
        )

        raw_response = (
            llm_service.generate(
                prompt
            )
        )

        plan_result = (
            _parse_plan(
                raw_response
            )
        )

        # ====================================================
        # VALIDATE LLM TOOL SELECTION
        # ====================================================

        valid_tools = [
            tool_name
            for tool_name
            in plan_result.tools
            if tool_name
            in available_tools
        ]

        # Remove duplicates while preserving order.

        valid_tools = list(
            dict.fromkeys(
                valid_tools
            )
        )

        if not valid_tools:

            raise ValueError(
                "Planner returned no valid tools."
            )

        planner_source = (
            "llm"
        )

        planner_error = (
            None
        )

    except Exception as exc:

        # ====================================================
        # FALLBACK PLANNER
        # ====================================================

        plan_result = (
            _fallback_plan(
                question
            )
        )

        # Validate fallback tools against registry as well.

        valid_tools = [
            tool_name
            for tool_name
            in plan_result.tools
            if tool_name
            in available_tools
        ]

        valid_tools = list(
            dict.fromkeys(
                valid_tools
            )
        )

        planner_source = (
            "fallback"
        )

        planner_error = str(
            exc
        )

    # ========================================================
    # TRACE
    # ========================================================

    trace.append({
        "node":
            "planner",

        "status":
            "success",

        "source":
            planner_source,

        "intent":
            plan_result.intent,

        "plan":
            valid_tools,

        "reasoning":
            plan_result.reasoning,

        "error":
            planner_error,
    })

    # ========================================================
    # STATE UPDATE
    # ========================================================

    return {
        "intent":
            plan_result.intent,

        "plan":
            valid_tools,

        "plan_reasoning":
            plan_result.reasoning,

        "planner_source":
            planner_source,

        "planner_error":
            planner_error,

        "current_step": (
            valid_tools[0]
            if valid_tools
            else None
        ),

        "trace":
            trace,
    }