from typing import Any, Dict, List, Optional

from typing_extensions import TypedDict


class AgentState(TypedDict, total=False):
    """
    Shared state passed between InsightFlow LangGraph nodes.

    The state contains both:

    1. Stable orchestration fields used by the runtime.
    2. Dynamic tool outputs produced by registry-defined tools.

    Dynamic outputs are stored inside ``tool_outputs`` so
    future tools can introduce outputs without requiring the
    AgentState schema to be modified.
    """

    # ========================================================
    # REQUEST
    # ========================================================

    dataset_id: str

    question: str

    # ========================================================
    # UNDERSTANDING / PLANNING
    # ========================================================

    # Analytical intent identified by the planner.
    #
    # Examples:
    # aggregation
    # visualization
    # forecasting
    # relationship_analysis
    # dataset_context

    intent: Optional[str]

    # Ordered execution plan.
    #
    # Example:
    #
    # [
    #     "sql",
    #     "visualization",
    #     "insight",
    # ]

    plan: List[str]

    # Explanation generated by planner/replanner.

    plan_reasoning: Optional[str]

    # "llm" or "fallback"

    planner_source: Optional[str]

    # Planner-specific failure information.

    planner_error: Optional[str]

    # Tool currently selected for execution.

    current_step: Optional[str]

    # ========================================================
    # TOOL EXECUTION
    # ========================================================

    # Successfully executed tools.

    executed_tools: List[str]

    # Raw result returned by every tool.
    #
    # Example:
    #
    # {
    #     "sql": {
    #         "success": True,
    #         "generated_sql": "...",
    #         "result": [...]
    #     }
    # }

    tool_results: Dict[str, Any]

    # ========================================================
    # DYNAMIC TOOL OUTPUTS
    # ========================================================

    # Generic container for promoted registry outputs.
    #
    # Example:
    #
    # {
    #     "generated_sql": "...",
    #     "sql_result": [...],
    #     "forecast_result": [...],
    #     "anomaly_result": {...}
    # }
    #
    # IMPORTANT:
    #
    # Future tools should place their declared outputs here
    # instead of requiring new AgentState fields.

    tool_outputs: Dict[str, Any]

    # ========================================================
    # EXISTING ANALYTICS OUTPUTS
    # ========================================================
    #
    # These fields remain for backward compatibility with
    # the existing API, tests, frontend, and orchestration
    # components.
    #
    # The executor may promote known outputs both here and
    # inside tool_outputs.

    generated_sql: Optional[str]

    sql_result: Any

    visualization: Any

    statistical_findings: List[Any]

    insight: Optional[str]

    # ========================================================
    # RETRY CONTROL
    # ========================================================

    retry_count: int

    max_retries: int

    # ========================================================
    # REPLANNING / RECOVERY
    # ========================================================

    replan_count: int

    max_replans: int

    failed_tool: Optional[str]

    last_tool_error: Optional[str]

    # ========================================================
    # WORKFLOW CONTROL
    # ========================================================

    error: Optional[str]

    completed: bool

    # ========================================================
    # OBSERVABILITY
    # ========================================================

    trace: List[
        Dict[str, Any]
    ]

    # ========================================================
    # FINAL RESPONSE
    # ========================================================

    final_response: Optional[
        Dict[str, Any]
    ]